version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build
          command: yarn build

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test